# Generated by Django 3.2.3 on 2021-09-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='-', max_length=100, verbose_name='Назва архіву')),
                ('create_date', models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата створення документа')),
                ('doc_count', models.IntegerField(default=0, verbose_name='Кількість документів')),
                ('zip_file', models.FileField(max_length=500, null=True, upload_to='archive/', verbose_name='Файл архіву')),
            ],
            options={
                'verbose_name': 'Архів',
                'verbose_name_plural': 'Архіви',
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
    ]
